### ISSUE TITLE
Problems connecting to registered console

### ISSUE THREAD

**Issue by Scachi** [ktnrg45/pyremoteplay#9]
I am running windows 10 (Version 21H2, Build 19044.1706) with python 3.8.13 via miniconda and did install your pyremoteplay via pip

I have an odd issue connecting to my ps5.
I followed your instructions and did the registering via the cli.
Everthing seemed to work fine as the remote play pin screen closed on my TV screen when I entered the pin number in the cli.

when I try to connect to my PS5 IP with 
`pyremoteplay 192.168.178.25`
I get:
```
ERROR:asyncio:Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF..., 1234, None)>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF..., 1234, None)>)>
Traceback (most recent call last):
  File "C:\Users\scachi\miniconda3\envs\psrpdev\lib\asyncio\proactor_events.py", line 548, in _loop_reading
    res = fut.result()
  File "C:\Users\scachi\miniconda3\envs\psrpdev\lib\asyncio\windows_events.py", line 812, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\scachi\miniconda3\envs\psrpdev\lib\asyncio\windows_events.py", line 500, in finish_recv
    return ov.getresult()
OSError: [WinError 1234] Am Endpunkt des Zielnetzwerks des Remotesystems wird kein Dienst ausgeführt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\scachi\miniconda3\envs\psrpdev\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\scachi\miniconda3\envs\psrpdev\lib\asyncio\proactor_events.py", line 569, in _loop_reading
    self._protocol.error_received(exc)
AttributeError: '_SocketProtocol' object has no attribute 'error_received'
ERROR:pyremoteplay.session:Could not detect host at: 192.168.178.25
ERROR:pyremoteplay.__main__:Session Failed to Start: Host @ 192.168.178.25 is not reachable.
```

When I run pyremoteplay-gui it reports "No Devices Found".
I can go to Options, click "Add Device", enter the same IP there and I get a popup "Device found" "Found Device at 192.168.178.25"
When I go back to [Home] screen now I can click on my PS5 and connect to it just fine. I can disconnect and reconnect fine as long as I don't close the gui window.
Closing and reopening the gui and it won't detect my PS5 again. I have to go to "Options" again and remove, then add the host to be able to connect again.

But I can't get any connection to my PS5 without the GUI at all.
I disabled all firewall and security settings I was able to without any success.
Any idea what is going on here ?

I can use the official remoteplay app and chiaki fine without any issues.

**Comment by ktnrg45** [comment]
Seems to be a new issue with asyncio that is likely caused by a Windows update. Can reproduce on my Windows machine. Implemented some workarounds for this and is working on my machine with release 0.7.0. Feel free to re-open this issue if you are still having issues.
